The probability an unfair die rolls a number is proportional to that number.  Pick two of these unfair, N-sided die (you choose the N) and sum the values.  

Write a simulation to estimate the mean and the variance of the sum of the dice.

In [32]:
import numpy as np
import random

In [162]:
def roll_dice(N):
    """Roll an unfair, N-sided die with probabilities proportional to the number on each face."""
    probabilities = [i/N for i in range(1, N+1)]
    ## this gives me a list of probabilities for each number on the dice, i.e. [1/6, 2/6, 3/6, etc] 
    choose = random.choices(range(1, N+1), weights=probabilities)[0]
    # here, I select the first item in the list (we're only choosing one item, FWIW.. we could use "k=x" for more)
    return choose

def simulate_dice_sum(num_trials, N):
    """
    Simulate and estimate the mean and variance of their sum.
    """
    sample_sum = 0
    results = []
    for i in range(num_trials):
        dice1 = roll_dice(N)
        dice2 = roll_dice(N)
        sample_sum += dice1 + dice2  
        ## this is the sum of the two dice rolls, which we keep adding to throughout the trials
        results.append(dice1 + dice2)
        ## Collect the sum of 
    mean = sample_sum / num_trials  # we just divide the total sum by the number of trials in the sim
    variancev2 = np.var(results)
    ## Variance is sum of the squared distances of each term in the distribution from the mean (μ), 
    ### divided by the number of terms in the distribution (N)
    return mean, variance, variancev2, results


In [163]:
a = roll_dice(6)
b = roll_dice(6)

In [164]:
np.array([a, b])

array([4, 3])

In [165]:
c = np.empty(2)

In [166]:
c

array([2.5e-323, 4.9e-324])

In [167]:
c = np.append(c, np.array([a, b]), axis=0)

In [168]:
c

array([2.5e-323, 4.9e-324, 4.0e+000, 3.0e+000])

In [169]:
np.random.rand(2, 2)

array([[0.14948514, 0.73820459],
       [0.39507423, 0.07785157]])

In [170]:
# Example usage:
mean, variance, variancev2, results = simulate_dice_sum(100000, 8)
print("Mean:", mean)
print("Variance:", variance)


Mean: 11.34128
Variance: 7.774487961600016
